[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    regression: Markers for regression tests.
    registration: Markers for tests related to user registration.
    authorization: Markers for tests related to user authorization.
    courses: Markers for tests related to courses.
